### ISSUE TITLE
predicate class for patient_has_disease?

### ISSUE THREAD

**Issue by BassamNa** [MaastrichtU-IDS/semanticscience#10]
Hi
I'm using SIO ontology to represent a medical records for patients, I have noted there is a Patient class and disease class, but which class can I use to represent a predicate "patient_has_disease"
i.e I want a class name for a predicate that link a patient to disease.
also same thing for diagnose (link patient to diagnose)

thanks

**Comment by micheldumontier** [comment]
The most generic predicate you can use is "has attribute" to link a patient
to a disease or to a diagnosis.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com

**Comment by BassamNa** [comment]
thanks Michael very much
