### ISSUE TITLE
Complex Numbers

### ISSUE THREAD

**Issue by jpmccu** [MaastrichtU-IDS/semanticscience#101]
I'd like to propose three subclasses to sio:Number: sio:ComplexNumber, sio:RealNumber and sio:ImaginaryNumber.

Definitions:

```
Class: sio:ComplexNumber
SubClassOf: sio:Number
EquivalentClass: sio:Number and sio:hasPart exactly 1 sio:ImaginaryNumber and sio:hasPart exactly 1 sio:RealNumber

Class: sio:ImaginaryNumber
SubClassOf: sio:Number
EquivalentClass: sio:Number and sio:hasQuality some sio:Imaginary

Class: sio:RealNumber
SubClassOf: sio:Number
EquivalentClass: sio:Number and sio:hasQuality some sio:Real
```

The use of existence qualities might be a bit literal on the math side, but if you like it we can run with it. I would suggest a way to handle quaternions, etc if I actually understood them. :-)

**Comment by micheldumontier** [comment]
Ok, I added 3 classes: 
complex number: http://semanticscience.org/resource/SIO_001443
real number: http://semanticscience.org/resource/SIO_001442
imaginary number: http://semanticscience.org/resource/SIO_001441

in SIO, both real and imaginary numbers are types of complex numbers, just depends whether the real or imaginary part is zero.
complex numbers have both real and imaginary parts, and real and imaginary numbers are pairwise disjoint.

**Comment by micheldumontier** [comment]
@jpmccu let me know if this works for you.

**Comment by jpmccu** [comment]
Sorry this took so long, yes, this looks like it will work. We are now modeling using it.
