### ISSUE TITLE
Term request: Isoform

### ISSUE THREAD

**Issue by NuriaQueralt** [MaastrichtU-IDS/semanticscience#102]
Dear SIO developers,

We need to represent protein isoforms for brain research in the [BIND project](https://bindproject.eu/). Our data models are based on SIO based EJP RD models. Could it be possible to ask you to mint a new term for 'Isoform', which could be a subclass of sio:Protein? or do you have another suggestion how to represent them in SIO? 

With kind regards,
Núria

**Comment by micheldumontier** [comment]
Hi Nuria. I've added a new class: 'protein isoform' to the ontology.

http://semanticscience.org/resource/SIO_001445

**Comment by micheldumontier** [comment]
@NuriaQueralt let me know if this is good for you.

**Comment by NuriaQueralt** [comment]
Hi @micheldumontier,

Thank you so much for your fast action taken on this. The addition suits our effort nicely. Thank you very much.

With kind regards,
Núria
