### ISSUE TITLE
request to add spirulina 

### ISSUE THREAD

**Issue by rashidsabbir** [MaastrichtU-IDS/semanticscience#104]
I noticed that "e. coli" is included in the ontology as a subclass of "unicellular-organism." Would it be possible to also include "spirulina" also as a subclass of "unicellular-organism?" This is a bacteria that is of interest in one of the projects I am involved in. However, the project is a materials science project, so it doesn't necessarily make sense to include it in our ontology. It is of interest because it is a nutritional supplement and there is ongoing research on using spirulina to create a biodegradable plastic. From Science Direct, spirulina is defined as "Spirulina is symbiotic, multicellular, and filamentous blue-green microalgae with symbiotic bacteria that fix nitrogen from air. It is recognizable by the arrangement of the multicellular cylindrical trichomes in an open left-hand helix along the entire length."

**Comment by micheldumontier** [comment]
Hi, I would instead recommend that you code the organism using the NCBI taxonomy.  "http://purl.obolibrary.org/obo/NCBITaxon_XXXXXX", where XXXX is the taxon identifier.

**Comment by rashidsabbir** [comment]
That's fair. I thought about it more and I agree the term probably doesn't belong in SIO.
