### ISSUE TITLE
Questions about some types is SIO supporting?

### ISSUE THREAD

**Issue by BassamNa** [MaastrichtU-IDS/semanticscience#11]
Hi
I have a disease resource rdf and many resources in emr system such as diagnoses and patient, disease for example it has properties (id, name, description, link_to-DOID)
I want to make a type for each property, for example id is SIO_000115 and name is SIO_000116.
but I don't know what type of link_to-DOID that link me a disease to doid ontology, is SIO_001171 i.e database cross-reference good?

also I want two predicate types (has_diagnoses, has_disease), is SIO support ?
thanks

**Comment by micheldumontier** [comment]
If you want to use SIO in lieu of SKOS, then yes, you can create an
instance of a database cross-reference, and use the 'refers-to' property to
link the two items.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com

**Comment by BassamNa** [comment]
thanks Michel, is there are properties ("has_disease" for links a patient with disease - also "has_diagnose" for link a patient with it's diagnoses)???
thanks again :)

**Comment by micheldumontier** [comment]
No - there are no such domain-specific properties in SIO

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com

**Comment by BassamNa** [comment]
thanks :)
really sorry about too questions but I'm considering in your ontology :) 
if most of classes included in SIO and there are a few isn't exist, what advice me create a new or extend a SIO 
thanks again Mr.Michel

**Comment by micheldumontier** [comment]
Proposals for new classes are always welcome. If you need more specific
relations, then I recommend that you create a new ontology that imports SIO
and extends it in the way you see fit.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com

**Comment by BassamNa** [comment]
thanks a lot Michel.
