### ISSUE TITLE
holding multi addresses?

### ISSUE THREAD

**Issue by BassamNa** [MaastrichtU-IDS/semanticscience#12]
Hi 
In standard EHR system that build the patient records using HL7 standard, the patient demographic has multi address, i.e may be the patient live in (country1, city2, street1..) but in other visit to hospital live in other address (country2, city2, street2...), how can I do modeling this scenario in SIO, AS I noted In current version in SIO:
?patient ?country "Syria"
?patient ?city "Damascus"
?Patient ?country "Germany"
?patient ?city "Berlin"

As you note there is no way to say Damascus city for Syria country and Berlin city for Germany country

wish it's clear question :)
thanks

**Comment by micheldumontier** [comment]
Hi Bassam,
  What we do is we make an instance of a country or city first, then
associate it in a meaningful way.

:patient :lives-in :Berlin .

:Berlin rdf:type sio:city .
:Berlin dct:title "Berlin"@en .
:Berlin sio:is-contained-in :Germany .

:Germany rdf:type sio:Country .
:Germany dct:title "Germany"@en .

m.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com
