### ISSUE TITLE
about SIO design ?

### ISSUE THREAD

**Issue by BassamNa** [MaastrichtU-IDS/semanticscience#13]
Hi 
I'm preparing a master thesis "using linked data in health",
I'm concerned in SIO, and I want to ask 2 questions about SIO design:
1- Why SIO classes not a clear name, but it's numeric format, i.e (SIO_010299) not a disease for example???

2- why SIO ontology declare every thing as owl class,  i.e:  first_name is property (domain is person and rage is string), but in SIO first_name is also class not a property, while foaf for example I note it declare it's classes and property a it object oriented concept?

wish it's clear
thanks :)

**Comment by micheldumontier** [comment]
1. The numeric format alleviates the potential for mis-understanding from a label.  That being said, we do offer label containing URIs e.g. http://semanticscience.org/resource/disease , but these are not guaranteed to be stable.
2. Making all kinds of things a class makes it easier to manage in an ontology. Moreover, it becomes possible to create class hierarchies for information related entities such as titles or names.  Pushing things into classes also reduces the number of relations that one needs to learn, which is especially true of the linked data vocabularies - they have limited potential for reuse outside of their domain.

**Comment by BassamNa** [comment]
thanks :)
