### ISSUE TITLE
Human vs person?

### ISSUE THREAD

**Issue by jpmccu** [MaastrichtU-IDS/semanticscience#15]
If human is a subclass of organism, what is the difference between human and person, a subclass? Does there really need to be two separate classes? If so, the distinction should be clearer in the definitions of human and person.

**Comment by dlmcguinness** [comment]
Thanks.  This is another one that surfaced in our review attempting to reuse for some study-related NIH-like applications.  I am trying to have good reasons to explain to potential (re)users of the ontology (and minimize distinctions that I need to explain if there is no compelling reason for the distinction).

**Comment by micheldumontier** [comment]
Person really is a socio-legal role, which is typically applied to humans, but can also include non-humans such as animals, corporations, etc.  so in this respect, the role needs to be more generic than human.

**Comment by micheldumontier** [comment]
i will move the person class to a new class 'specialized object' under 'object'

**Comment by micheldumontier** [comment]
done.
