### ISSUE TITLE
Provide an OWL version that uses literalized URIs

### ISSUE THREAD

**Issue by jpmccu** [MaastrichtU-IDS/semanticscience#17]
The sameAs linked data is fine, but a full OWL file with that transformation would be helpful for people who prefer to work fully against the literalized URIs.

**Comment by micheldumontier** [comment]
That's here. 

https://github.com/micheldumontier/semanticscience/tree/master/ontology/sio/release

i'll add a link on the home page

**Comment by micheldumontier** [comment]
a6ed84a51e58a9ba7d93e2dfc3d1988a095c1730

**Comment by micheldumontier** [comment]
in code. will be in next release  08cadb0
