### ISSUE TITLE
Please normalize your IRI for the ontology to be the same (in terms of the preferred and base IRI)

### ISSUE THREAD

**Issue by ElisaKendall** [MaastrichtU-IDS/semanticscience#18]
The IRI in the rdf:RDF namespace declarations for the ontology is:

  xmlns:ns2="http://semanticscience.org/resource/"

The namespace declared for the ontology is

http://semanticscience.org/ontology/sio.owl

The namespace stated as preferred in the annotations is

```
<ns3:preferredNamespaceUri rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://semanticscience.org/resource/</ns3:preferredNamespaceUri>
<ns3:preferredNamespaceUri rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">http://sio.semanticscience.org</ns3:preferredNamespaceUri>
```

Only two of these are identical.  The ontology IRI and RDF namespace IRIs should be the same, and best practice for large ontologies is to use a "slash-style" IRI if it is intended to be used for server side resolution.  You might take a look at the Cool URIs paper on the W3C site, at https://www.w3.org/TR/cooluris/ -- "hash IRIs" are more appropriate for small ontologies that are quite stable and that are not intended to be extended - whereas the SIO ontology is already quite large, and lots of people are extending it and working with it.

If your intent is that the ontology should be published at http://semanticscience.org/ontology/sio.owl, then a better namespace approach would be to use:

  xmlns:sio="http://semanticscience.org/ontology/sio/"

and 

  <rdf:Description rdf:about="http://semanticscience.org/ontology/sio/">
        <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Ontology"/>

and

```
<ns3:preferredNamespaceUri rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://semanticscience.org/ontology/sio/</ns3:preferredNamespaceUri>
```

so that they are all the same, and so that the ontology can be consistently imported by others.  Also, if you are publishing the ontology in RDF/XML serialized OWL (which is still preferred by many folks in the community and works with the most tools), the extension on the filename should be ".rdf" rather than ".owl".  This allows you to publish it in Turtle (".ttl") or other forms using the same URI and filename, but with the proper filename extensions per the standard W3C standards and according to the registered MIME type.

**Comment by micheldumontier** [comment]
yes - so this "http://sio.semanticscience.org" should be the homepage link. so i used rdfs:seeAlso now

**Comment by micheldumontier** [comment]
The base namespace is http://semanticscience.org/resource/ .  should i declare this as anyURI?

**Comment by micheldumontier** [comment]
.owl is a recommended file ending. https://www.w3.org/TR/owl-ref/#MIMEType
.rdf is just as ambiguous, since both RDF and OWL have multiple serializations.

if you request application/xml as a mime type, you get it

**Comment by ElisaKendall** [comment]
The real question is whether you want to use semanticscience.org/resource/ or semanticscience.org/ontology/ or semanticscience.org/resource/sio/ as the URI for the ontology.  Yes, you can define the ontology with a different IRI than the resources inside it, but that can be very confusing for new users.  It took me a little while to figure it out, and our students were shaking their heads and didn't realize doing so was even possible.

If you serve everything at the semanticscience.org/resource/, you should probably use that in all cases.  Then in the ontology declaration, you would use the same URI that you're using for everything else:

  <rdf:Description rdf:about="http://semanticscience.org/resource/sio/">

with the sio added to support the ontology name.  It might be better to use http://semanticscience.org/resource/sio/ everywhere, and then the file name would be sio.rdf, and tools that navigate people's directories to create xml catalogs would understand exactly what to do if they save it locally.

Another way to make this more explicit, especially if the ontology IRI is different from the IRI for the content in the body of the ontology is to use an explicit owl:Ontology statement rather than rdf:Description together with an rdf:type of owl:Ontology.  But that's a matter of taste more than anything else.

I would prefer not to see ".owl" in the IRIs, even if you are not using it much in the body of the ontology - that approach has been deprecated in the OWL community, and although the document claims that you can use .owl, that's ambiguous -- a number of folks in the standards community are advocating using .rdf for RDF/XML serialized OWL (which is what you are doing), .ttl if it's Turtle, etc.

I hope this helps :).

**Comment by micheldumontier** [comment]
ok. still a bit confused :)

The document URI is http://semanticscience.org/ontology/sio.owl

Inside the document, we see

  <rdf:Description rdf:about="http://semanticscience.org/ontology/sio.owl">

```
<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Ontology"/>

<ns0:versionInfo rdf:datatype="http://www.w3.org/2001/XMLSchema#string">1.26.0</ns0:versionInfo>

<ns0:versionIRI rdf:resource="http://semanticscience.org/ontology/sio-v1.26.0-release.owl"/>
```

and each concept is linked to the ontology IRI

  &lt;rdf:Description rdf:about=&quot;http://semanticscience.org/resource/SIO_000073&quot;&gt;
    &lt;rdf:type rdf:resource=&quot;http://www.w3.org/2002/07/owl#Class &quot;/&gt;
    &lt;ns7:isDefinedBy rdf:resource=&quot;http://semanticscience.org/ontology/sio.owl &quot;/&gt;
  &lt;/rdf:Description&gt;

how is this not best practice?
