### ISSUE TITLE
What is the provenance for instrument being a subclass of HeterogeneousSubstance

### ISSUE THREAD

**Issue by dlmcguinness** [MaastrichtU-IDS/semanticscience#20]
It seems like it may be a direct child of material entity.

**Comment by micheldumontier** [comment]
for better or worse SIO sees all complex objects, particularly those built with plastics and metals as heterogeneous substances

**Comment by dlmcguinness** [comment]
One issue is that instrument is under that.  Not all instruments are built from plastics and metals - some are legal or paper documents .  For example, i have often heard epidemiology questionnaires referred to as instruments.  it is very odd for them to end up being chemical or biological entities.

**Comment by micheldumontier** [comment]
anything made of atoms is a chemical entity.

**Comment by dlmcguinness** [comment]
So online questionnaires are chemical entities?  that feels very unnatural.

**Comment by micheldumontier** [comment]
Online questionnaires are information content entities, which can take any number of material forms.

**Comment by jpmccu** [comment]
Right, but the ICEs themselves are not material entities. Do you have a better place to classify what's known as a survey instrument, as expressed here? http://njaes.rutgers.edu/evaluation/resources/survey-instrument.asp

**Comment by micheldumontier** [comment]
ICEs are not asserted to be material entities, they are objects.

m.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com

**Comment by jpmccu** [comment]
I think the point is that instruments are sometimes ICEs and not material entities.
