### ISSUE TITLE
Polymer classes are unsound

### ISSUE THREAD

**Issue by jpmccu** [MaastrichtU-IDS/semanticscience#29]
sio:OrganicPolymer is not a subclass of sio:Polymer. Further, sio:Monomer is sio:isDirectPartOf some sio:Biopolymer, but sio:Biopolymer is a sibling class to nucleic acids, proteins, and other organic polymers. What are "biological components" in sio:Biopolymer, and why do they seem to exclude all of the siblings of Biopolymer?

**Comment by micheldumontier** [comment]
ok. update the definition so that you get the entailment, but only on reasoning.
