### ISSUE TITLE
Should sio:concept be part of sio.owl

### ISSUE THREAD

**Issue by csarven** [MaastrichtU-IDS/semanticscience#32]
http://semanticscience.org/resource/concept is defined but doesn't appear in sio.owl. Should that be added?

**Comment by micheldumontier** [comment]
the ontology release files are here: https://github.com/micheldumontier/semanticscience/tree/master/ontology/sio/release
 
sio-release.owl is the current SIO file. two relevant files then are the sio-subset-labels.owl and sio-subset-equivs.owl
