### ISSUE TITLE
add class for "protein family" (collection of protein domains)

### ISSUE THREAD

**Issue by sillitoe** [MaastrichtU-IDS/semanticscience#34]
Hi,

I couldn't find an existing class for anything approximating a "protein family" (closest I could find was "collection of 3d molecular structures").

Suggested description:
A protein family is a collection of related protein domains.

Thanks.

**Comment by micheldumontier** [comment]
added: http://semanticscience.org/resource/protein-family.rdf

**Comment by sillitoe** [comment]
Great, many thanks
