### ISSUE TITLE
How to model fasting blood measurements?

### ISSUE THREAD

**Issue by jpmccu** [MaastrichtU-IDS/semanticscience#35]
A lot of medical lab tests are done in a fasting state, and can be very important to do that way. How should we relate some sort of fasting quality or process (not sure which) to the blood attribute?

```turtle
:fasting_glucose_concentration a sio:Concentration;
  sio:hasUnit :mg_per_dl;
  sio:hasValue 80;
  sio:inRelationTo :blood_sample_glucose;
  sio:isAttributeOf :blood_sample.

:blood_sample_glucose a chebi:17234; # glucose
  sio:isPartOf :blood_sample.

:blood_sample a uberon:0000178, sio:Sample; # blood
  sio:isDerivedFrom :patient.

:patient a sio:Human.
```

Let's assume that we should indicate a fasting state:

```turtle
sio:Fasting a owl:Class; # or maybe in an extending ontology, doesn't matter.
  rdfs:subClassOf sio:BiologicalQuality.

:patient_fasting a sio:Fasting;
  sio:isAttributeOf :patient.
```

In this case, what is the right relation between `:patient_fasting` and either `:blood_sample` or `:fasting_glucose_concentration`? Should we be modeling fasting as a process instead?

**Comment by micheldumontier** [comment]
That's right, fasting is a process of reducing or abstaining from food and/or drink. The individual participant in the fasting process would be said to have the quality of 'hypoglycemia', as exemplified by a measurement of their blood sugar level.   both the quality and the measurement are attributes of the individuals.

**Comment by jpmccu** [comment]
Right, but do we need to use a specialization of the patient to say that a measurement was taken within a particular context/state, or is there a better way to relate them?

**Comment by micheldumontier** [comment]
you can specify the time and place of the measurement value, and you can attribute it to the individual and/or quality/part for which it was taken. alternatively, you the measurement value can be the product of a measurement process involving the individual and/or their relevant qualities.

**Comment by jpmccu** [comment]
While it may not be reasonable to say that a sample was created as a product of a fasting process, is there a way to state that it was creating *during* the fasting process?

**Comment by micheldumontier** [comment]
yes, you create a sub-process (e.g. sample collection) that is part of the fasting process.
