### ISSUE TITLE
'exists at'

### ISSUE THREAD

**Issue by neilotte** [MaastrichtU-IDS/semanticscience#44]
I saw on ontobee that 'exists at' is described in SIO as holding between an entity and a time measurement, but 'exists at' already has a URI in BFO where it holds between an entity and a temporal region. 

http://purl.obolibrary.org/obo/BFO_0000108

**Comment by micheldumontier** [comment]
ok... so what's your point?

**Comment by neilotte** [comment]
It's an OBO Foundry principle not to use the same relations in another ontology and then to assign them your own definitions. Hence I am suggesting you change the label of the relation.   

http://www.obofoundry.org/principles/fp-001-open.html

**Comment by leechuck** [comment]
I don't think it's the same relation as identity of relations in the Semantic Web is defined by their IRI, not their label. Also, SIO is not OBO Foundry.

**Comment by neilotte** [comment]
Ah, thanks leechuck. I was thinking it was in the foundry. Nevermind.
