### ISSUE TITLE
Add term for subcellular localization

### ISSUE THREAD

**Issue by folago** [MaastrichtU-IDS/semanticscience#45]
This ontology is used to specify the type of ProteinAnnotation in Bioschema.
We would like to have a subcellular_localization type of annotation in order to specify the subcellular localization prediction for a protein. 
We have a tool that provide this kind of annotation http://busca.biocomp.unibo.it/ and we would like to annotate its output according to bioschema.

Suggested description: The cells are subdivided into functionally-distinct membrane-bound compartments. Some major constituents are: extracellular space, cytoplasm, nucleus, mitochondria, Golgi apparatus, endoplasmic reticulum (ER), peroxisome, vacuoles, cytoskeleton, nucleoplasm, nucleolus, nuclear matrix and ribosomes.

So far we are using GO to reference the localization, e.g. http://amigo.geneontology.org/amigo/term/GO:0005634, http://amigo.geneontology.org/amigo/term/GO:0009707.

**Comment by micheldumontier** [comment]
Hi, so we have 'subcellular entity' as SIO_001400  (https://bioportal.bioontology.org/ontologies/SIO/?p=classes&conceptid=http%3A%2F%2Fsemanticscience.org%2Fresource%2FSIO_001400). is this what you want?

**Comment by folago** [comment]
I think ProteinAnnotation is not part of BioSchema anymore.
Anyways SIO_001400 looks good, we could add it to the schema either as voice in the controlled dictionary or as a suggestion.

I am closing this issue since it refers to an obsolete type.
