### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by ronaldcornet** [MaastrichtU-IDS/semanticscience#51]
https://semanticscience.org/resource/SIO_000432.rdf is misspelled as millenium, instead of millennium
Further, it is of type "time interval", where I would see this as a "time period", in line with the given definition "a period of 1000 years".

Further, I think the terminology on quantities with units needs straightening:
I miss properties for "magnitude" and "quantity".
See, e.g., http://www-ksl.stanford.edu/knowledge-sharing/ontologies/html/physical-quantities/MAGNITUDE.html#:~:text=Units%20of%20measure%20are%20scalar,equal%20to%20the%20original%20quantity.
"The magnitude of a constant-quantity is a numeric value for the quantity given in terms of some unit-of-measure. For example, **the magnitude of the quantity** 2 kilometers in the **unit-of-measure meter** is the real number 2000."

So in sio I would like to be able to express:
:my2km_run sio:has_attribute [a sio:length; sio:has_quantity [sio:has_magnitude 2000; sio:has_unit uo:meter]]
Alternatively:
:my2km_run sio:has_attribute [a sio:length; sio:has_attribute [a quantity; sio:has_magnitude 2000; sio:has_unit uo:meter]]

Would it make sense to add both sio:has_quantity and sio:has_magnitude?

Otherwise, an example on how to represent this in sio would be welcomed.

**Comment by micheldumontier** [comment]
Thanks Ronald. let's discuss. 
1) What do you see as the difference between "time interval" and "time period"?
2) we use sio:has-value to specify the magnitude of a quantity. sio:has-unit can be used to link to the appropriate unit.
 see https://github.com/MaastrichtU-IDS/semanticscience/wiki/DP-Measurements

**Comment by ronaldcornet** [comment]
Happy to discuss, Michel.

1. I read here: https://dictionary.cambridge.org/dictionary/english/interval : a period between two events or times
In my opinion the focus is here on "period", not on the events or times. 
In other words, a one-week period becomes a one-week interval when we know start- or end-time.
And here: https://dictionary.cambridge.org/dictionary/english/period
a period is a length of time. I think that's exactly what is intended to be represented.

To me there are situations in which it is/seems/sounds strange to talk about intervals, whereas using periods make perfect sense.

2. "we use sio:has-value to specify the magnitude of a quantity. sio:has-unit can be used to link to the appropriate unit."
I see that this is in line with https://en.wikipedia.org/wiki/Physical_quantity :
"A physical quantity can be expressed as the combination of a numerical value and a unit"

However, this means that now measurement observations (length etc) are represented using "has-value" and "has-unit", whereas observations with categorical outcomes (e.g., gender, diagnosis), can't use has-value. Would you suggest "has-quality" for that?
I.e. would you agree with: gender has-quality masculine

I'm trying to get my head around this, to ensure we represent things as consistently and reproducibly as possible (you may have been in touch with Marco Roos and/or Mark Wilkinson as well). Hence my asking.


Thanks for the DP on measurements!

**Comment by micheldumontier** [comment]
i guess the way i saw it was that a period is just an interval of a specified length of time... i can adjust the definition accordingly.

**Comment by micheldumontier** [comment]
You are correct that the pattern only works with numeric values. SIO tackles the categorical outcomes a bit differently. I documented an example for diagnosis based on a cognitive test on https://github.com/MaastrichtU-IDS/semanticscience/wiki/DP-Measurements

**Comment by ronaldcornet** [comment]
This one:
 'obtaining a diagnosis'
 subClassOf
 'process'
 and 'has agent' some 'physician'
 and 'has target' some 'patient'
 and 'has input' some 'cognitive test result'  #e.g.  measurement value of 22
 and 'has output some ('diagnosis' and 'is attribute of' some 'patient')

So the shorthand seems "patient has-attribute diagnosis"
Where the diagnosis is detected/represented by it being an output-of "obtaining a diagnosis"

I'll experiment more with that.

**Comment by micheldumontier** [comment]
yes, that's the idea. would very much like to hear any counterexamples or problems with this. it's untested!

**Comment by micheldumontier** [comment]
@ronaldcornet any update to share?

**Comment by ronaldcornet** [comment]
Nothing at the moment @micheldumontier , nothing before the end of this year either. It's on the longlist, teaching until X-mas, basically.

**Comment by micheldumontier** [comment]
will close this for now.
