### ISSUE TITLE
has frequency and is frequency of

### ISSUE THREAD

**Issue by leechuck** [MaastrichtU-IDS/semanticscience#6]
Both 'has frequency' and 'is frequency of' are subclasses of 'has measurement value', however, only 'has frequency' should be a subclass there, and 'is frequency of' should be a subclass of 'measurement value of' or similar. Currently, domain/range restrictions would not be inherited appropriately.

**Comment by micheldumontier** [comment]
as far as i can tell, this is not a problem with SIO. if i download the file with protege i don't see it asserted or entailed. neither does it show up like that in bioportal...
