### ISSUE TITLE
Which Best Diseases Ontology?

### ISSUE THREAD

**Issue by BassamNa** [MaastrichtU-IDS/semanticscience#8]
Hi
sorry if my question it's trivial, but I'm beginner in health semantic web and I'm master student So I don't have a team specially medical team (work alone according to university regulations)

I want to link patient records in RDF format to disease ontology?
which best disease ontology? can help me?
for example I see Human disease ontology in bio2rdf project

thanks.

**Comment by micheldumontier** [comment]
Hi Bassam,
  Yes, I would suggest using the disease ontology
http://disease-ontology.org/

m.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com

**Comment by BassamNa** [comment]
thansk

As you know to link my rdf to disease-ontology I need the IRIs
I find many sites such as bio2rdf and many and many IRO for the ontology,where can I find ontology and it's endpoint also whrere can get IRIs to make queries?

sorry to my questions and thanks again

**Comment by micheldumontier** [comment]
That's a good question to ask the DO people!

m.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com

**Comment by BassamNa** [comment]
thanks :)
I think by the way to link my data to Bio2RDF ontologies, for example how to link to DO in Bio2RDF?

thanks
