### ISSUE TITLE
New term for percentile

### ISSUE THREAD

**Issue by jonrkarr** [MaastrichtU-IDS/semanticscience#87]
Name: percentile

Description: A position, such as 95%, within a statistical distribution.

Subclass of: SIO_000052

**Comment by jonrkarr** [comment]
@micheldumontier we're planning to use SIO as part of a new standard for the results of biosimulations. SIO will be used to annotate the semantic meaning of dimensions of the results that represent time points, spatial coordinates, etc. The new standard is part of a larger effort to make biomodels more reusable and composable (See https://biosimulators.org/ and https://biosimulations.dev/ for more info).

To use SIO, we need to add a few additional terms.

**Comment by micheldumontier** [comment]
Hi. sorry for the delay - busy time of year.

I added a new term "percentage"; id: SIO_001413

it is a subclass of ratio.

**Comment by micheldumontier** [comment]
ok, added percentile (SIO_001416) as a quantile (SIO_001414), which is then a dimensionless quantity
