### ISSUE TITLE
Federated queries 

### ISSUE THREAD

**Issue by BassamNa** [MaastrichtU-IDS/semanticscience#9]
Hi
sorry again michel, but I try to make many discussions with experts in medical semantic web science to get the talent :)
I have my medical data in virtuoso server and want to link my data to DO for diseases,
 my objective is to make federated SPARQL queries i.e traversal on my data then diseases ontology:

Must I upload the ontology in virtuoso server also, or not there is other way to link my data to IRIs of DO, what you advice me?

e.g your Bio2RDF, how you access to DO and other ontologies, do you upload it in your server ?
again I'm sorry about trivial questions :)
thanks :)

**Comment by micheldumontier** [comment]
Bassam,
  I appreciate that you need help. Unfortunately, I just don't have the
time to answer all your questions. You'll really need to reach out to
others!  you can try the HCLS semantic web list.
https://lists.w3.org/Archives/Public/public-semweb-lifesci/

m.

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com
