### ISSUE TITLE
Google group "Content unavailable"

### ISSUE THREAD

**Issue by stimon** [MaastrichtU-IDS/semanticscience#90]
Hi,

It is not an issue per se, but is the discussion group still available? 
I'm retaking a development involving SIO, and I will likely have doubts along the process.

**Comment by micheldumontier** [comment]
Hi, just feel free to post here.

**Comment by micheldumontier** [comment]
please open a specific issue if you want to discuss.

**Comment by stimon** [comment]
Will do, thank you Michel!
