### ISSUE TITLE
Modeling Tensors

### ISSUE THREAD

**Issue by jpmccu** [MaastrichtU-IDS/semanticscience#92]
We are modeling tensors in our materials science ontology, and SIO is just about there (except actually having tensor-related classes). Here's how I think we can proceed:

```
Class: tensor
SubClassOf: 'mathematical entity'

Class: number
SubClassOf: tensor
Annotations: altLabel "rank 0 tensor"

Class: 'rank nonzero tensor'
SubClassOf: tensor, 'ordered list'
EquivalentClass: tensor and 'has proper part' only (tensor and 'has attribute' some 'ordinal position')

Class: vector
SubClassOf: 'rank nonzero tensor'
EquivalentClass: tensor and 'has proper part' only number
Annotations: altLabel "rank 1 tensor"

Class: matrix
SubClassOf: 'rank nonzero tensor'
EquivalentClass: tensor and 'has proper part' only vector
Annotations: altLabel "rank 2 tensor"

Class: matrix
SubClassOf: 'rank nonzero tensor'
EquivalentClass: tensor and 'has proper part' only vector
Annotations: altLabel "rank 2 tensor"
```

Any rank `N` tensor can be defined from here as equivalent to:

```
tensor and 'has proper part' only 'rank N-1 tensor'
```

The numbers in question will determine the kind of tensor and what it means, and we can throw in kernel functions as a subclass if anyone knows how the specifics should go

Aside: it's kind of hard to tell the distinction between 'ordered list' and 'sequence', but that might just be me.

**Comment by micheldumontier** [comment]
Hi Jamie - thanks for this submission. weirdly, i didn't get a notification on the post (even though all the settings indicate i should!)
i'll add scalar, vector, matrix, and tensor to SIO. 

in your text above - you have matrix defined twice - was there another definition that you intended to provide or was it just a copy paste error?

however, we should discuss the representation of the rank nonzero tensor. when we think of a vector or a matrix, we would consider a 1 and 2 dimensional object respectively. you correctly point to 'ordered list' as an option. however, ordered lists must necessarily have a structural list item ( that specifies its ordinal position and uses 'refers to' relationship to point to the object of interest). are you ok with this? 

crucially, the question is whether we must also do this for scalars. obviously, if i make a number a subclass of scalar, then it will break what we expect from a rank 0 tensor. (an ordered list with one item).

**Comment by jpmccu** [comment]
Yes, copy/paste. I think I started to define a rank 3 tensor and forgot. :-)

I don't think a rank 0 is an ordered list. It's a tensor in 0-dimensional space, hence it has no order since there are no dimensions to order it in.

**Comment by micheldumontier** [comment]
ok. have a look.

**Comment by jpmccu** [comment]
That'll do, thanks!

**Comment by micheldumontier** [comment]
Thanks!
