### ISSUE TITLE
Please help add new data property terms.

### ISSUE THREAD

**Issue by leonqli** [MaastrichtU-IDS/semanticscience#93]
Please help add the following data properties:

'has value less than'
'has value less than or equal to'
'has value greater than'
'has value greater than or equal to'

Thanks for your great work! 
Leon

**Comment by micheldumontier** [comment]
Hi!
  it would be useful for me to understand your use case. can you give some examples of how you would use these relations?

**Comment by leonqli** [comment]
Hi @micheldumontier Thanks for your reply!

Currently we use sio:has-value to model an endpoint that has a certain IC50 value. We wonder if you can support not just "equal to", i.e. '=', but also 'greater than' ('>'), e.g. >80nM, or 'greater than or equal to', i.e. '>=', etc. 

Thanks,
Leon

**Comment by micheldumontier** [comment]
Using OWL, you can encode this as a datatype restriction on the value of the property

https://www.w3.org/TR/owl2-syntax/#Datatype_Restrictions

**Comment by leonqli** [comment]
Hi @micheldumontier 

Thanks for looking into it. I still don't know how to use the method you suggested. For example, I have an endpoint which is >=0.16 uM, how should I apply the restriction of ">=" to the following triples? Thanks for your help!

```
:endpoint <http://semanticscience.org/resource/has-value> 0.16^^<http://www.w3.org/2001/XMLSchema#float>
:endpoint <http://semanticscience.org/resource/has-unit>  <http://purl.obolibrary.org/obo/UO_0000064>
```

**Comment by micheldumontier** [comment]
you'd write it like this:
```
:endpoint 
  rdf:type
  [ 
      rdf:type owl:Restriction ;
      owl:onProperty <http://semanticscience.org/resource/has-value ;
      owl:someValuesFrom [ 
          rdf:type rdfs:Datatype ;
          owl:onDatatype xsd:float;
          owl:withRestrictions ( [ xsd:minExclusive "0.16"^^xsd:float ])
      ]
] .
```
