### ISSUE TITLE
why is submolecule not a subclass of covalently connected entity?

### ISSUE THREAD

**Issue by cmungall** [MaastrichtU-IDS/semanticscience#94]
![image](https://user-images.githubusercontent.com/50745/107701840-4c76f980-6c6e-11eb-9aaf-385cb7a4be75.png)

Submolecule: 
 - mereological sum of covalently bonded atoms.

A covalently connected molecular entity: 
 - mereological sum of _a collection of_ covalently bonded atoms.

I'm trying to interpret the significance of the difference in textual definitions, which are almost identical. Isn't the "collection of" implicit in the first definition?

Minor aside: the text def of CCE says "CCME" but the label of the class is CCE. I recommend following OBO style and not including the term name in the def to avoid redundancy/sync issues

**Comment by mbrush** [comment]
Going to piggyback on this ticket to ask a couple other questions about the SIO chemical entity hierarchy.  
1. The phrase  "molecular entity" is used in the textual definitions in several  chemical entity subclasses:
    a. **Chemical substance**: A chemical substance is a chemical complex of weakly interacting _molecular entities_, and may include bulk solvent.
    b. **Submolecular entity**: A submolecular entity is a part of a _molecular entity_.
    c. **Covalently connected entity** : A covalently connected _molecular entity_ is the mereological sum of a collection of covalently bonded atoms.

But ‘molecular entity’ is not a SIO class, and the phrase is not defined clearly in these definitions.   This makes it hard to understand what these SIO classes mean and how they are meant to be related to other SIO classes. Does the notion of a ‘molecular entity’ as used in these text definitions map to a specific SIO class? 

2.	I noticed SIO:chemical entity is asserted to be equivalent to CHEBI:23367 molecular entity. I think that SIO:chemical entity more closely maps to ChEBI:24431 ‘chemical entity’.

**Comment by micheldumontier** [comment]
Thanks for reporting these issues. I've taken both of your feedback and refactored the ontology and modified definitions.

![sio-refactored](https://user-images.githubusercontent.com/993852/108414894-10730400-722d-11eb-8ec4-bec9da7a13a7.png)

**chemical substance**: A chemical substance is a chemical entity composed of two or more weakly interacting chemical entities.

**molecule**: A molecule is single chemical entity composed of fully covalently bonded atoms.

**submolecular entity:** A submolecular entity is a part of a molecule or a particle smaller than a molecule.

**submolecule**: A submolecule is any part of a molecule.

**Comment by cmungall** [comment]
Thanks! I see the change on OLS, so I will close this now!
