### ISSUE TITLE
Question about the definition of "chemical substance"

### ISSUE THREAD

**Issue by leonqli** [MaastrichtU-IDS/semanticscience#99]
The definition of chemical substance (http://semanticscience.org/resource/SIO_011126) said, "two or more weakly (non-covalently) interacting chemical entities", which doesn't covered single chemical entity substance, e.g. pure substance. 

Is it possible to consider to change the definition like what is defined in ChEBI, "A chemical substance is a portion of matter of constant composition, composed of molecular entities of the same type or of different types." 

Thanks for your great work!

**Comment by micheldumontier** [comment]
Pure substances, that is, those substances composed of one chemical entity, are specified as 'homogeneous substance'
http://semanticscience.org/resource/SIO_010463 ... this is further partitioned into chemical elements and allotropes.
